# SPDX-License-Identifier: MIT-0
---
# tasks file for sat_reg

- name: Importing registration tasks
  ansible.builtin.import_tasks: reg_to_sat.yml
  # when: satellite_host is defined and satellite_admin_account is defined |
  #  and satellite_admin_account_password is defined and activation_key_name |
  #   is defined and satellite_org_name is defined
